(set-background-color "#000000")
(setq vc-follow-symlinks t)
;; (set-frame-parameter nil 'alpha-background 100)
;; (add-to-list 'default-frame-alist '(fullscreen . maximized))
;; (add-to-list 'initial-frame-alist '(fullscreen . maximized))
(org-babel-load-file (expand-file-name "config.org" user-emacs-directory))
(put 'downcase-region 'disabled nil)
